name: Build HelloWorld Project for Linux

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-linux-x86-64:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
        
    - name: build
      run: >
        cmake -DCMAKE_INSTALL_PREFIX=dist -DCMAKE_BUILD_TYPE=Release .;
        make install;
        
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hello-android-arm-64
        path: dist/*
